<a href="https://colab.research.google.com/github/Devendra1patel/Datascience_colab_code/blob/main/advance_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [5]:
arr = np.ones((3,4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [8]:
arr*9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [26]:
# empty((x,y),i) --> it gives array of (x,y) dimention with random value
# np.empty((3,4), int)
np.empty((3,4))

array([[4.6977691e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [28]:
#eye give you squre matrix based on 5(x)
# np.eye(5)
np.eye(5, dtype = int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
import pandas as pd

In [32]:
# Data frame - it is multiple rows and collection.
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [33]:
# extra topics
import random

In [34]:
random.choice((1,2,3,4,5,6))

2

In [35]:
random.choice('devendra')

'a'

In [36]:
random.randrange(1,1000)

626

In [37]:
random.random()

0.007652365549400519

In [41]:
lis = [1,2,3,4,5,6,7,8,9,10]
random.shuffle(lis)
lis

[6, 8, 4, 1, 2, 3, 7, 5, 10, 9]

In [45]:
random.uniform(7,14) # a no between 7 and 14 . it not select rendomly it follow some patter (some distribution are thier)

7.684893447895076

numpy also can do jobs which can doable by random librery

In [46]:
np.random.rand(2,3)

array([[0.20661872, 0.33898668, 0.26399153],
       [0.80643859, 0.72873455, 0.18763546]])

In [47]:
np.random.rand(1)

array([0.73729136])

In [48]:
np.random.randn(2,3)

array([[-0.70745733,  1.14831092,  0.18080441],
       [ 1.69164436,  1.1347364 ,  0.25871147]])

In [49]:
# np.random.random_sample() #range of o to 1 , where 1 is excluded

0.20043842715239513

In [50]:
np.random.randint(1,5,size = (3,4)) #where 1,5 --> is range of randomNum, size=(3,4) -->array

array([[2, 1, 3, 4],
       [2, 4, 2, 3],
       [3, 3, 1, 1]])

In [51]:
arr.size

12

In [52]:
arr.shape

(3, 4)

In [53]:
arr.ndim # ndim --> dimention of an array

2

In [55]:
#we can reshape the array - using reshape
# condition -dimention must mltiple of arr.size4
arr.reshape(6,2)
arr.reshape(2,6)
arr.reshape(12,)
arr.reshape(12,1)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
arr.reshape(2,-1) #when you know the row only

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
arr.reshape(-1,3)  #when you know the column only

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])